version: "3.8"

services:
  app:
    build: .
    container_name: library_app
    ports:
      - "3000:3000"  # Exposes your Node app to host
    env_file:
      - .env
    depends_on:
      - mysql
    command: npm run dev

  mysql:
    image: mysql:8
    container_name: library_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
